### PR TITLE
Reference correct tuple type on recent julia master

### PR DESCRIPTION
**Pull request by kshyatt**
Should allow `NDTensors` to precompile on recent julia master versions.

### CODE REVIEW

**Comment by mtfishman** [comment]
Cool, thanks. It looks like we could just be using Base's tuple hashing here at this point based on recent comments here: https://github.com/JuliaLang/julia/issues/37073, but good to fix. I guess we don't have nightly tests, is that generally good practice? I found they would fail fairly often so they didn't seem super useful.

**Comment by kshyatt** [comment]
IDK if we need them. I just wanted to take care of this in case someone (me, for example) wanted to use the higher dimensional tuples that Julia now provides without allocing.

**Comment by mtfishman** [comment]
I'm confused, how did these tests break? Was that actually from the changes you made here?

**Comment by kshyatt** [comment]
I don't think so, the same tests fail on `master`.

**Comment by mtfishman** [comment]
I think these are just failing since the tests are running against the latest registered ITensors v0.1.41 but the latest NDTensors is only compatible with the unregistered ITensors v0.2.0. Just an annoying part of doing CI in this way.

**Pull request merged**
