### PR TITLE
exponentiation for block-sparse matrices (block-diagonal)

### PR DESCRIPTION
**Pull request by orialb**
The NDTensors part for https://github.com/ITensor/ITensors.jl/issues/394 .

### CODE REVIEW

**Comment by orialb** [comment]
hmm, are the tests for this package running as part of the ITensors.jl test suite?

**Comment by mtfishman** [comment]
Looks good, thanks! We just haven't set up CI here yet, for now we are being lazy and testing NDTensors through ITensor functionality (since the tests would often mirror each other anyway, and NDTensors is mostly being developed for internal use in ITensors.jl at the moment).

**Comment by mtfishman** [comment]
Though it is great that you added tests, and we should set up CI here even though the coverage is pretty bad right now.

**Comment by orialb** [comment]
Maybe you can setup CI such that PRs to NDTensors run the ITensors test suite?

**Comment by mtfishman** [comment]
Not a bad idea, we could look into it.

**Pull request merged**
